class_name ObjectManagerConfig

enum OBJECT{
    NOONE = 0, 

    PROJECTILE = 1, 
    DAMAGEPART = 2, 

    GAMECOLLECT = 10, 
    SUN = 11, 
    SUN_BRAIN = 12, 
    SUN_JALAPENO = 13, 

    COIN = 20, 
    COIN_SILVER = 21, 
    COIN_GOLD = 22, 
    COIN_DIAMOND = 23, 

    PARTICLES = 100, 
    PARTICLES_PEA_SPLATS = 101, 
    PARTICLES_SNOW_PEA_SPLATS = 102, 
    PARTICLES_FIRE_SPLATS = 103, 
    PARTICLES_PUFF_SPLATS = 104, 
    PARTICLES_SPIKE_SPLATS = 105, 
    PARTICLES_BUTTER_SPLATS = 106, 
    PARTICLES_MELON_SPLATS = 107, 
    PARTICLES_WINTER_MELON_SPLATS = 108, 
    PARTICLES_GLOOM_SPLATS = 109, 
    PARTICLES_ICE_FIRE_SPLATS = 110, 
    PARTICLES_SPIKE_MELON_SPLATS = 111, 

    PARTICLES_SPLASH = 201, 
    PARTICLES_RISE_DIRT = 202, 
    PARTICLES_ICE_TRAP = 203, 

    PROJECTILE_SPRITE = 300, 
    PROJECTILE_SPRITE_PEA = 301, 
    PROJECTILE_SPRITE_SNOW_PEA = 302, 
    PROJECTILE_SPRITE_FIRE_PEA = 303, 
    PROJECTILE_SPRITE_PUFF = 304, 
    PROJECTILE_SPRITE_PUFF_BIG = 305, 
    PROJECTILE_SPRITE_SPIKE = 306, 
    PROJECTILE_SPRITE_KERNAL = 307, 
    PROJECTILE_SPRITE_BUTTER = 308, 
    PROJECTILE_SPRITE_MELON = 309, 
    PROJECTILE_SPRITE_WINTER_MELON = 310, 
    PROJECTILE_SPRITE_GLOOM = 311, 
    PROJECTILE_SPRITE_ICE_SWORD = 312, 
    PROJECTILE_SPRITE_ICE_FIRE_PEA = 313, 
    PROJECTILE_SPRITE_ICE_SPEAR = 314, 
    PROJECTILE_SPRITE_SPIKE_MELON = 315, 

    MAX = 1000
}
